week10/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

week10/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('vote_ajax/', views.vote_ajax, name='vote_ajax'),
    path('setcookie', views.setcookie),
    path('showcookie', views.showcookie),
]

week10/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

week10/polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect

from .models import Question, Choice
from django.template import loader
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt



def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question, 'question_id':question_id})

@csrf_exempt
def vote_ajax(request):
    question_id = request.POST['question_id']
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return {
            "msg": "Vote unsuccess, please try again. (Reason: Choice.DoesNotExist)",
            'stauts': "unsuccess"
        }

    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        choice_list = []
        for choice in question.choice_set.all():
            choice_list.append({'text':choice.choice_text,'votes':choice.votes})
        response = {'msg':"success", 'data':choice_list}
        return JsonResponse(response)


def setcookie(request):
    html = HttpResponse("<h1>Django Cookie Tutorial</h1>")
    if request.COOKIES.get('visits'):
        html.set_cookie('mycookie', 'Welcome Back')
        value = int(request.COOKIES.get('visits'))
        html.set_cookie('visits', value + 1)
    else:
        value = 1
        text = "Welcome for the first time"
        html.set_cookie('visits', value)
        html.set_cookie('mycookie', text)
    return html
 


def showcookie(request):
    show = request.COOKIES['mycookie']
    html = f"<center> New Page <br>{show}</center>"
    return HttpResponse(html)


def deletecookie(request):
    if request.COOKIES.get('visits'):
       response = HttpResponse("<h1>Cookie deleted</h1>")
       response.delete_cookie("visits")
    else:
        response = HttpResponse("<p>need to create cookie before deleting</p>")
    return response

week10/polls/templates/polls/detail.html
{% load static %}
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script src = "{% static 'polls/main.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote_ajax' %}" method="post">
  {% csrf_token %} {% for choice in question.choice_set.all %}
  <input
    type="radio"
    name="choice"
    id="choice{{ forloop.counter }}"
    value="{{ choice.id }}"
  />
  <input type="hidden" name="question_id" value="{{question_id}}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
  ><br />
  {% endfor %}
  <input id="submit" type="button" value="Vote" />
</form>

<div id="results" hidden>
  <h2 id="message">Message</h2>
  <ul id="options">

  </ul>
</div>

week10/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li>
    <a href="{% url 'polls:detail' question.id %}"
      >{{ question.question_text }}</a
    >
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

week10/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize
    }}
  </li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>